### ISSUE TITLE
is there any plan to update edp-keycloak-operator?

### ISSUE THREAD

**Issue by lutartur** [epam/edp-keycloak-operator#101]
is there any plan to update edp-keycloak-operator?

master branch contains functionality that is not in the release branch

**Comment by MykolaMarusenko** [comment]
Hi @lutartur!

Regarding the [issue](https://github.com/epam/edp-keycloak-operator/issues/102), we have created a new 1.23.0 release. The corresponding [release tag](https://github.com/epam/edp-keycloak-operator/releases/tag/v1.23.0) is available in the repository. You can also review the updated [changelog](https://github.com/epam/edp-keycloak-operator/blob/master/CHANGELOG.md#v1230---2024-10-29). Both the image and Helm chart are now available with this release tag. The OperatorHub release is planned for next week.

Best regards,
Mykola

**Comment by lutartur** [comment]
Awesome! thanks
