### ISSUE TITLE
Allow multiple redirect URIs

### ISSUE THREAD

**Issue by thriqon** [epam/edp-keycloak-operator#12]
**Is your feature request related to a problem? Please describe.**
For our use case, applications may be reachable with multiple, equally acceptable URLs. Keycloak supports this out-of-the-box. The KeycloakClient.Spec does not support setting multiple URLs.

**Describe the solution you'd like**
The spec should have an additional field `redirectURIs` as `[]string`, defaulting to the singleton with the `webUrl` (e.g. here?
https://github.com/epam/edp-keycloak-operator/blob/master/pkg/client/keycloak/adapter/gocloak_adapter.go#L578 )

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by SergK** [comment]
@thriqon Our team has scheduled your request for the next sprint. We estimate that it will be completed within the next week.
