### ISSUE TITLE
Do not delete Keycloak items on Kubernetes object deletion by default

### ISSUE THREAD

**Issue by julianbuettner** [epam/edp-keycloak-operator#18]
**Is your feature request related to a problem? Please describe.**
I just renamed the `KeycloakRealm` object and accidentally deleted the staging realm.  
(renaming + `kubectl apply` = delete + create?)
There were backups in place, so everything turned out fine, but it's a hell of a trap to fall in.

**Describe the solution you'd like**
I would like to _not_ have my realms deleted.  
Maybe an annotation like `delete-keycloak-object-on-kubernetes-deletion` with a default of `false`,
which has to be explicitly set to `true` to keep the current behaviour. Examples could be updated, so the issue is
directly recognized by users not thinking much (like me).

(Compare `"helm.sh/resource-policy": "keep"`)

**Describe alternatives you've considered**
Not using this product, because it contains a rather big footgun.  
But I would like to use it in production, because it's otherwise exactly what I need.

**Additional context**
N/A

**Comment by SergK** [comment]
@julianbuettner Hello, I think we can make this field immutable and not allow such operations but force the user to create a new realm. @zmotso, what do you think? Since Keycloak API doesn't allow such stuff, recreation operations can be dangerous.

**Comment by zmotso** [comment]
@SergK @julianbuettner Hi. Yes, we can add some annotation/parameter to the CR to prevent deletion of the realm. We can implement it shortly (in a week or two).

**Comment by julianbuettner** [comment]
It appears to me the issue is fixed, so I will close this issue now.   
Thank you for implementing this request.   
Is there an estimated time of the next release?

**Comment by SergK** [comment]
@julianbuettner, please expect till the end of this week.
