### ISSUE TITLE
Missing `bearerOnly` in CRD `KeycloakClient` / `keycloakclients.v1.edp.epam.com/v1`

### ISSUE THREAD

**Issue by julianbuettner** [epam/edp-keycloak-operator#24]
**Is your feature request related to a problem? Please describe.**
Hello,

I want to specify a keycloak client with the parameter `bearerOnly: true`.  
However, this key currently does not exist for CRD `KeycloakClient` and is ignored and set to false by default.

**Describe the solution you'd like**
I would like to be able to provide `bearerOnly`, or maybe provide an
entire dictionary of extra key value pairs which should be sent with the `POST` or `PUT` to keycloak.

**Describe alternatives you've considered**
Alternatives are doing it manually or write some extra script to update the value to the desired state.

**Additional context**
Keycloak has many more possible keys defined in their
[documentation](https://www.keycloak.org/docs-api/22.0.1/rest-api/index.html#ClientRepresentation).
Due to the amount of keys and possible future changes, being able to provide an object with arbitrary key value pairs might be a viable solution. Having only `bearerOnly` would be fine for my current personal use case.

**Comment by zmotso** [comment]
@julianbuettner Hi
It seems like a small change. We will probably include this feature in the next sprint.

**Comment by SergK** [comment]
The latest version 1.20.0 has been released. Please let us know if you encounter any issues.
