### ISSUE TITLE
Missing fields in CRD KeycloakClient / keycloakclients.v1.edp.epam.com/v1 

### ISSUE THREAD

**Issue by fndejong** [epam/edp-keycloak-operator#25]
**Is your feature request related to a problem? Please describe.**
Hello,

First off, thank you for your amazing work on this Operator.

We are currently evaluating the usage of the EDP Keycloak Operator in our GitOps workflows. For this, we are examining the CRDs and try to migrate our existing realm.json export to separate K8S manifests. 

For the most part, this seems doable, but our front-end login is not compatible with the options the EDP Keycloak Operator currently offers. We need to explicitly set the _WebOrigins_ and _implicitFlowEnabled_ fields.

**Describe the solution you'd like**
We'd like to have the option to specify more fields in the KeycloakClient spec. 

**Describe alternatives you've considered**
We could not export this client and keep it in the existing realm.json.

**Additional context**
We've already forked this repository and started working on defining and binding the missing fields. This can be done in a backwards compatible manner, since the _WebOrigins_ was already set with the existing _WebUrl_ field. The _implicitFlowEnabled_ can be defaulted to `false`.

We've been struggling a bit with getting the tests to work, so I'll open up a PR where I'll gladly take up your advice how to test it properly

**Comment by zmotso** [comment]
Hi @fndejong, thank you for your feedback. 
Currently, we are working on similar issues https://github.com/epam/edp-keycloak-operator/issues/24.
We plan to provide all missing fields to the KeycloakClient CRD in the next version.

**Comment by zmotso** [comment]
@fndejong Yes, you can close PR. Good advice, I will add a comment to #24.
