### ISSUE TITLE
Allow creating Authorization Policies/Permissions for a Client

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#28]
**Is your feature request related to a problem? Please describe.**

Currently There is no way to add access to a new client to give them permissions to do token-exchange or impersonation. These settings need to be added to the realm-management client in the Realm.

**Describe the solution you'd like**

A CR that allows a user to create a Authorization Policy or Permission with a specific target client in a realm or a field in the KeycloakClient CR to add permissions directly.

**Describe alternatives you've considered**

We are currently using the Keycloak's Operator, but it requires wiping the realm to re-import any changes. Other than that you would need to add the permissions manually which is tedious.

**Comment by zmotso** [comment]
Hi @dougkirkley.
As I understand, you want to manage these properties of the keycloak client by CR.

![image](https://github.com/epam/edp-keycloak-operator/assets/10484729/eefd781f-33a3-4a68-8963-a13358345ce6)

Currently, we don't have this functionality. After looking into it, we will consider your request for possible new feature implementation.

**Comment by zmotso** [comment]
We can add to the KeycloakClientSpec array of permissions and policies. It is better to recreate almost the same structs on the operator side. But without ID, and maybe some fields should accept unique names instead of uuid ids 
`ClientAuthorizationPolicy.Clients	[ "e2dc7ea7-7386-4ddc-bddc-b6c59b5263f1" ]` -> `ClientAuthorizationPolicy.Clients [ "client1" ]`)
Example:
```go
type KeycloakClientSpec struct {
	//...
	AuthorizationPolicies *[]AuthorizationPolicy `json:"authorizationPolicies,omitempty"`
}

type AuthorizationPolicy struct {
	Config           *map[string]string `json:"config,omitempty"`
	DecisionStrategy *string             `json:"decisionStrategy,omitempty"`
	Description      *string            `json:"description,omitempty"`
	Logic            *string            `json:"logic,omitempty"`
	Name             *string            `json:"name,omitempty"`
	Owner            *string            `json:"owner,omitempty"`
	Policies         *[]string          `json:"policies,omitempty"`
	Resources        *[]string          `json:"resources,omitempty"`
	Scopes           *[]string          `json:"scopes,omitempty"`
	Type             *string            `json:"type,omitempty"`
	// Here, we can add the types you need first and leave the rest for future implementation.
	RoleAuthorizationPolicy *RoleAuthorizationPolicy `json:"roleAuthorizationPolicy,omitempty"`
	JSAuthorizationPolicy *JSAuthorizationPolicy `json:"jsAuthorizationPolicy,omitempty"`
	ClientAuthorizationPolicy *ClientAuthorizationPolicy `json:"clientAuthorizationPolicy,omitempty"`
	TimeAuthorizationPolicy *TimeAuthorizationPolicy `json:"timeAuthorizationPolicy,omitempty"`
	UserAuthorizationPolicy *UserAuthorizationPolicy `json:"userAuthorizationPolicy,omitempty"`
	AggregatedAuthorizationPolicy *AggregatedAuthorizationPolicy `json:"aggregatedAuthorizationPolicy,omitempty"`
	GroupAuthorizationPolicy *GroupAuthorizationPolicy `json:"groupAuthorizationPolicy,omitempty"`
}
```

You can create a pull request if you wish, and we will assist you with review and implementation. 
Alternatively, we can implement this in 1-2 weeks when we have time.

**Comment by zmotso** [comment]
We implemented Authorization Policies for keycloak clients.
CR example:
https://github.com/epam/edp-keycloak-operator/blob/47f06408da7402491826568a951920cb43ffe019/deploy-templates/_crd_examples/keycloakclient.yaml#L23

Currently, this feature is in muster brunch and will be included in the nearest release.
