### ISSUE TITLE
Deletion of CR where keycloak object no longer exists

### ISSUE THREAD

**Issue by beasteers** [epam/edp-keycloak-operator#40]
**Describe the bug**

Cannot delete CRs (KeycloakRealm, KeycloakClient) if the objects don't exist anymore.

**To Reproduce**

#### What did you do?

I was testing database bring up/bring down with FluxCD and I guess the reconciler didn't garbage collect the resources in the right order? Like I think it deleted the database before the Keycloak operator resources were deleted.

This could also happen if someone deletes the realm/client from the keycloak UI, you'd want to be able to recreate the resources from the operator instead of it ending up in a deadlock.

#### What did you expect to see?

If the Keycloak resources (realm, client, etc.) don't exist and you try and delete, the operator should continue as if the realm/client deletion was successful and proceed with deleting the custom resources. 

#### What did you see instead? Under which circumstances?

When I try and delete the realm and clients manually, the operator spits out these logs. The deletion never happens (even when force deleting them, it just hangs)
```
297fb6f21276", "name": "my-realm", "error": "failed to delete realm: error during keycloak resource deletion: failed to delete keycloak realm: unable to delete realm: 404 Not Found: Realm not found."}

2024-04-01T20:56:57Z ERROR an error has occurred while handling keycloak client {"controller": "keycloakclient", "controllerGroup": "v1.edp.epam.com", "controllerKind": "KeycloakClient", "KeycloakClient": {"name":"directus-keycloak-client","namespace":"cluster-config"}, "namespace": "cluster-config", "name": "directus-keycloak-client", "reconcileID": "82cb5284-307c-41f7-8e6a-235b16f5b0c2", "name": "directus-keycloak-client", "error": "unable to get keycloak realm: unable to get keycloak realm from ref: failed to get realm: unable to get realm: 404 Not Found: Realm not found."}
```

I managed to fix the realm issue by recreating it a couple of times in the UI until the operator was happy, but now I'm seeing these errors because the secret containing the client secret has been deleted by now.
```
1352d40b215f", "name": "directus-keycloak-client", "error": "unable to serve keycloak client: unable to put keycloak client: error during convertCrToDto: unable to get secret, err: unable to get secret from ref: failed to get secret keycloak-client.directus-keycloak-client.secret: Secret \"keycloak-client.directus-keycloak-client.secret\" not found"}
```

**Kubernetes cluster type:**

Azure (AKS) - deployed 1.20.0 with helm

**Comment by zmotso** [comment]
@beasteers, thank you for your feedback. We'll take a look at this issue.

**Comment by zmotso** [comment]
@beasteers  Your case is an expected result. The current implementation of the operator only supports removing resources if the parent resources (e.g., client, realm) exist. We don't plan to implement this as it leads to significant changes.

You can remove the finalizer for blocked resources, which will fix the problem.
![Screenshot 2024-04-12 at 11 58 22](https://github.com/epam/edp-keycloak-operator/assets/10484729/eb32c997-7dd8-4f23-8738-308b700da5e8)

**Comment by beasteers** [comment]
But couldn't you just catch the exception thrown when it doesn't exist and just continue deleting the custom resource?

**Comment by zmotso** [comment]
Unfortunately, our code structure doesn't allow this. To fix this, we need to refactor all controllers.
Closing this issue as we currently don't have plans to support this.
