### ISSUE TITLE
Add Scopes to Keycloak Client Authorizations

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#41]
**Is your feature request related to a problem? Please describe.**
When using the new Authorization field for KeycloakClient (Thanks for adding that feature), if the permission is scoped based, then the scope needs to exist in the Authorization Scopes for the Client.

**Describe the solution you'd like**
Add a Scopes field to the KeycloakClient Authorization spec

**Describe alternatives you've considered**
Manually adding the authorization scope e.g "token-exchange" allows the KeycloakClient to reconcile properly

**Additional context**
I am working on a branch for this now, but I'm currently stuck at the mock pieces because `make mocks` is hitting a nil pointer. If you could possibly point into the right direction of which piece I could have missed, I would love to get this PR in for your team.

**Comment by zmotso** [comment]
@dougkirkley You can open a draft pull request. I will check why the mocks aren't working.
