### ISSUE TITLE
Add Complicated Examples of Keycloak Auth Flows

### ISSUE THREAD

**Issue by dougkirkley** [epam/edp-keycloak-operator#72]
**Is your feature request related to a problem? Please describe.**
I have a more complicated auth flow similar to the default Browser flow but with X509 auth. I am having trouble getting it implemented

**Describe the solution you'd like**
I think it would be beneficial to have the default browser auth flow as an example using the operator. One with my exact flow would be much appreciated. Example provided below.

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
<img width="1191" alt="Screenshot 2024-07-10 at 8 02 40 AM" src="https://github.com/epam/edp-keycloak-operator/assets/25086366/91ba152f-abe4-47d8-a2c9-9cb0ad01fb24">

**Comment by Rolika4** [comment]
Hello @dougkirkley

Thank you for your questions.

Could you provide what version of Keycloak operator do you use?

We will try to add an example based on your request if all auth flow methods are supported

**Comment by dougkirkley** [comment]
Hello @Rolika4 

I am using version v1.21.0

**Comment by Rolika4** [comment]
Hello @dougkirkley

To find Keycloak CR examples you can navigate to [examples folder](https://github.com/epam/edp-keycloak-operator/tree/master/deploy-templates/_crd_examples).

Additionally, we added and encourage you to familiarise yourself with our [additional examples](https://github.com/epam/edp-keycloak-operator/blob/master/deploy-templates/_crd_examples/keycloakauthflow.yaml) on embedded authentication flow. Below is the screenshot that showcases these resources.

![Screenshot at Jul 24 11-42-32](https://github.com/user-attachments/assets/5ca1cb19-f82a-465a-8277-37bc7786a9a7)

**Comment by dougkirkley** [comment]
Awesome, thanks!

**Comment by Rolika4** [comment]
Hello, @dougkirkley 
Thank you for feedback. 

Unfortunately that your described still no implemented in Keycloak-operator, and you could configure necessary parameters manually. 

I close this issue, because I can't help you more. We implement this functionality as soon as possible, you can follow the implementation status by [ticket with this feature](https://github.com/epam/edp-keycloak-operator/issues/82).
