### ISSUE TITLE
Add DisplayName field to keycloakRealm

### ISSUE THREAD

**Issue by mostoja** [epam/edp-keycloak-operator#94]
I can't find a way to set displayName field for keycloakRealm

If there's no current way to set it right now it would be nice to add `displayName` field to keycloakRealm CRD.

**Describe alternatives you've considered**

**Additional context**

**Comment by zmotso** [comment]
@mostoja, thank you for bringing this up.

Currently, the operator does not support setting the `displayName` field for keycloakRealm. However, we have added this feature request to our backlog. It’s a relatively small change, and we hope to implement it soon.
