### ISSUE TITLE
SMTP configuration for realm

### ISSUE THREAD

**Issue by sherlant** [epam/edp-keycloak-operator#96]
Hello,
i try to configure smtp for realm, but i have found nothing about that in documentation/crds definition.
There is a way to do this ?

Thanks for advance.

**Comment by zmotso** [comment]
Hello @sherlant ,

Thank you for bringing this to our attention. Currently, our operator does not support configuring SMTP for realms. We will add this feature request to our backlog for future consideration.

**Comment by sherlant** [comment]
ok, thanks, have you a roadmap to share ?

**Comment by zmotso** [comment]
@sherlant No, we don't have a public roadmap.  
We plan to start working on this task roughly within the next month.

**Comment by zmotso** [comment]
@sherlant hi. We've implemented this feature.
Example of SMTP configuration: https://github.com/epam/edp-keycloak-operator/blob/master/deploy-templates/_crd_examples/keycloakrealm.yaml#L79
